### ISSUE TITLE
Writing content is breaking paths?

### ISSUE THREAD

**Issue by paulwalk** [fbacall/ro-crate-ruby#4]
Since the last update, `ROCrate::Writer.new(crate).write` has stopped working correctly. It now tries to write files to paths which have been truncated, and then just fails with error `No such file or directory @ rb_sysopen ....`. This fails identically with `ROCrate::Writer.new(crate).write_zip`.

As an example, the generated RO-Crate metadata file has this entry in it's root data entity `hasParts`:

```json
        {
          "@id": "txttocsvforphi.py"
        },
```

which corresponds to this data entity:

```json
    {
      "@id": "txttocsvforphi.py",
      "@type": "File",
      "path": "MIDATA001.108/tools/txttocsvforphi.py"
    },
```

This correctly represents the origin data, but it is being written to the target directory with the path `/tools/txttocsvforphi.py` (i.e. missing a component). The system then throws an exception:

`ERROR: No such file or directory @ rb_sysopen - MIDATA001.108/tools/txttocsvforphi.py`

Is there any reason not to use the path as the ID? This would seem safer (it would disambiguate two files with the same name in different folders)

**Comment by fbacall** [comment]
This may be because I have changed/broken the API for adding files and directories to the crate.

The second argument of `add_path` or `add_directory` is now the path within the crate (instead of the keyword argument `path:`).

**Comment by antleaf** [comment]
Thanks - have adjusted code to reflect that. The `ROCrate::Writer.new(crate).write` method writes what appears to me to be a completely correct RO-Crate metadata file, but then it raises a `ERROR: No such file or directory @ rb_sysopen` having written just one (empty) folder to the output folder.

**Comment by paulwalk** [comment]
Thanks - have adjusted code to reflect that. The ROCrate::Writer.new(crate).write method writes what appears to me to be a completely correct RO-Crate metadata file, but then it raises a ERROR: No such file or directory @ rb_sysopen having written just one (empty) folder to the output folder.

**Comment by fbacall** [comment]
I suspect this something to do with relative paths and working directories.

Is the code the same as you posted in #1 ?

Does it work if you use `add_file` with a `File` object rather than a path?

Currently the existence of the input files is not checked until it comes to writing :(

**Comment by paulwalk** [comment]
I suspected it was to do with relative paths, but I can't figure out what's going wrong.

> Is the code the same as you posted in #1 ?

Yes, although I changed the method calls to `add_file` and `add_directory` to:

`crate.add_file(path,path)`

> Does it work if you use add_file with a File object rather than a path?

I haven't tried that yet, but will do so - making tea for the kids right now so may be tomorrow :-)

> Currently the existence of the input files is not checked until it comes to writing :(

That doesn't impact my use case particularly, but I guess it could be an issue for others eventually.

**Comment by fbacall** [comment]
I'd be interested to hear more about your use case.

As it stands, I've only really considered my own, which is using RO crates as an exchange format to get data in/out of a web application.

**Comment by paulwalk** [comment]
My use case: I have two closely related use-cases:

1. I'm working on a project to (semi)automate the creation of versioned RO-Crate metadata files in a git repository, where each RO-Crate metadata file is tied to a particular commit in that repository, so that an RO-Crate can be generated retrospectively as required for any of those commits.
2. Ingesting one of those (zipped) RO-Crates into a data repository (based on Samvera), and unpacking it there.

I am also interested in the HTML Preview feature, making the RO-Crate itself a somewhat more re-usable 'research object'.

**Comment by paulwalk** [comment]
> Does it work if you use add_file with a File object rather than a path?

I have now tried this - it makes no difference.

**Comment by fbacall** [comment]
^ might possibly fix this.

Can I ask what OS you're using? And could you try running the tests (`$ rake test`)?

**Comment by paulwalk** [comment]
That fixed it!

I'm running on MacOSX but would be running this code on Linux in production.

Ran the tests:
`19 tests, 138 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed`

:-)

**Comment by fbacall** [comment]
Great! Paths are always finicky across different OSes. I'll look into adding OSX (and maybe Windows) environments to the CI.
